(()=>{
const scenes=window.CEN_SCENES; const $=id=>document.getElementById(id);
const state={idx:0,scale:1,x:0,y:0,tab:'summary',sheet:false,pointers:new Map(),lastDist:0,lastCenter:null,lastTap:0,baseScale:1};
const els={app:$('app'),splash:$('splash'),start:$('startBtn'),explorer:$('explorer'),viewport:$('viewport'),img:$('sceneImg'),hotspots:$('hotspots'),toast:$('sceneToast'),home:$('homeBtn'),mini:$('miniBtn'),miniMap:$('miniMap'),miniClose:$('miniClose'),miniItems:$('miniItems'),prev:$('prevBtn'),next:$('nextBtn'),far:$('farBtn'),near:$('nearBtn'),plus:$('plusBtn'),minus:$('minusBtn'),sheet:$('infoSheet'),sheetHandle:$('sheetHandle'),section:$('sectionLabel'),place:$('placeLabel'),infoIcon:$('infoIcon'),infoTitle:$('infoTitle'),infoOne:$('infoOne'),tabContent:$('tabContent'),journey:$('journeyBar')};
function scene(){return scenes[state.idx]}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function apply(anim=false){els.viewport.classList.toggle('anim',anim); const s=scene(); const min=s.minScale||1,max=s.maxScale||5; state.scale=clamp(state.scale,min,max); const limitX=(state.scale-1)*innerWidth*.48; const limitY=(state.scale-1)*innerHeight*.48; state.x=clamp(state.x,-limitX,limitX); state.y=clamp(state.y,-limitY,limitY); els.img.style.transform=`translate(calc(-50% + ${state.x}px), calc(-50% + ${state.y}px)) scale(${state.scale})`; updateHotspotPositions(); if(anim) setTimeout(()=>els.viewport.classList.remove('anim'),560)}
function load(i, opts={}){state.idx=clamp(i,0,scenes.length-1); const s=scene(); els.viewport.className='viewport '+(s.fit||'cover'); els.img.style.opacity=.25; els.img.onload=()=>{els.img.style.opacity=1;}; els.img.src=s.image; state.scale=opts.scale||1; state.x=0; state.y=0; render(); apply(true); showToast(`${s.icon} ${s.title}`,s.one)}
function render(){const s=scene(); els.section.textContent=s.section; els.place.textContent=s.title; els.infoIcon.textContent=s.icon; els.infoTitle.textContent=s.title; els.infoOne.textContent=s.one; renderTabs(); renderJourney(); renderMini(); renderHotspots(); els.prev.style.display=state.idx>1?'block':'none'; els.next.style.display=state.idx<scenes.length-1?'block':'none'}
function renderTabs(){document.querySelectorAll('.tabBtn').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab)); const s=scene(); els.tabContent.textContent=s[state.tab]||s.summary}
function renderJourney(){els.journey.innerHTML=scenes.slice(0,5).map((s,i)=>`<button class="journeyItem ${i===state.idx?'active':''}" data-i="${i}"><span class="jico">${s.icon}</span><span>${s.title.replace('언약궤와 ','')}</span></button>`).join(''); els.journey.querySelectorAll('button').forEach(b=>b.onclick=()=>load(+b.dataset.i,{scale:1.1}))}
function renderMini(){els.miniItems.innerHTML=scenes.slice(0,5).map((s,i)=>`<button class="miniItem ${i===state.idx?'active':''}" data-i="${i}">${s.icon} ${s.title}<br><small>${s.section}</small></button>`).join(''); els.miniItems.querySelectorAll('button').forEach(b=>b.onclick=()=>{els.miniMap.classList.add('hidden');load(+b.dataset.i,{scale:1.05})})}
function renderHotspots(){const s=scene(); els.hotspots.innerHTML=(s.hotspots||[]).map(h=>`<button class="hotspot" data-target="${h.target}" data-x="${h.x}" data-y="${h.y}">${h.label}</button>`).join(''); els.hotspots.querySelectorAll('.hotspot').forEach(b=>b.onclick=()=>{const id=b.dataset.target; const i=scenes.findIndex(s=>s.id===id); if(i>=0) load(i,{scale:1.18});}); updateHotspotPositions()}
function updateHotspotPositions(){els.hotspots.querySelectorAll('.hotspot').forEach(b=>{const x=+b.dataset.x,y=+b.dataset.y; b.style.left=x+'%'; b.style.top=y+'%'; b.classList.toggle('small',state.scale>2.15)})}
let toastTimer; function showToast(title,body){els.toast.innerHTML=`${title}<p>${body}</p>`; els.toast.classList.remove('hidden'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>els.toast.classList.add('hidden'),2100)}
function zoomTo(target){state.scale=clamp(target,scene().minScale||1,scene().maxScale||5); apply(true)}
function setOverview(){state.scale=1;state.x=0;state.y=0;apply(true); if(state.idx!==0)showToast('전체보기','성막 전체 조망으로 축소했습니다.')}
function go(delta){load(state.idx+delta,{scale:1.1})}
function dist(a,b){return Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)} function center(a,b){return {x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2}}
els.viewport.addEventListener('pointerdown',e=>{els.viewport.setPointerCapture(e.pointerId); state.pointers.set(e.pointerId,e); const now=Date.now(); if(now-state.lastTap<290 && state.pointers.size===1){zoomTo(state.scale<2?2.5:1); state.lastTap=0}else state.lastTap=now;});
els.viewport.addEventListener('pointermove',e=>{if(!state.pointers.has(e.pointerId))return; state.pointers.set(e.pointerId,e); const pts=[...state.pointers.values()]; if(pts.length===1 && state.scale>1.02){state.x+=e.movementX||0; state.y+=e.movementY||0; apply(false)} else if(pts.length>=2){const [a,b]=pts; const d=dist(a,b); const c=center(a,b); if(!state.lastDist){state.lastDist=d; state.lastCenter=c; return} const factor=d/state.lastDist; state.scale=clamp(state.scale*factor,scene().minScale||1,scene().maxScale||5); if(state.lastCenter){state.x+=c.x-state.lastCenter.x; state.y+=c.y-state.lastCenter.y} state.lastDist=d; state.lastCenter=c; apply(false)}});
['pointerup','pointercancel','pointerleave'].forEach(ev=>els.viewport.addEventListener(ev,e=>{state.pointers.delete(e.pointerId); if(state.pointers.size<2){state.lastDist=0;state.lastCenter=null}}));
window.addEventListener('popstate',e=>{if(!els.miniMap.classList.contains('hidden')){els.miniMap.classList.add('hidden'); history.pushState({cen:1},''); return} if(state.sheet){state.sheet=false; els.sheet.classList.add('compact'); history.pushState({cen:1},''); return} if(state.idx!==0){load(0,{scale:1}); history.pushState({cen:1},''); return} els.splash.classList.remove('hidden'); els.explorer.classList.add('hidden');});
document.querySelectorAll('.tabBtn').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderTabs()});
els.start.onclick=()=>{els.splash.classList.add('hidden'); els.explorer.classList.remove('hidden'); history.replaceState({cen:1},''); history.pushState({cen:2},''); load(0,{scale:1}); setTimeout(()=>zoomTo(1.08),250)};
els.home.onclick=()=>{ if(state.idx!==0) load(0,{scale:1}); else setOverview();}; els.mini.onclick=()=>els.miniMap.classList.toggle('hidden'); els.miniClose.onclick=()=>els.miniMap.classList.add('hidden'); els.prev.onclick=()=>go(-1); els.next.onclick=()=>go(1); els.far.onclick=()=>setOverview(); els.near.onclick=()=>zoomTo(3.2); els.plus.onclick=()=>zoomTo(state.scale+.45); els.minus.onclick=()=>zoomTo(state.scale-.45); els.sheetHandle.onclick=()=>{state.sheet=!state.sheet; els.sheet.classList.toggle('compact',!state.sheet)}; window.addEventListener('resize',()=>apply(false));
})();
